//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DhSoftDBEntities2 : DbContext
    {
        public DhSoftDBEntities2()
            : base("name=DhSoftDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MusteriTbl> MusteriTbl { get; set; }
        public virtual DbSet<SiparisDetayTbl> SiparisDetayTbl { get; set; }
        public virtual DbSet<SiparisTbl> SiparisTbl { get; set; }
        public virtual DbSet<UrunTbl> UrunTbl { get; set; }
    
        public virtual ObjectResult<SiparisFormu_Result> SiparisFormu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SiparisFormu_Result>("SiparisFormu");
        }
    
        public virtual ObjectResult<MusteriBilgi_Result> MusteriBilgi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MusteriBilgi_Result>("MusteriBilgi");
        }
    }
}
