//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiparisTbl()
        {
            this.SiparisDetayTbl = new HashSet<SiparisDetayTbl>();
        }
    
        public int SiparisID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<System.DateTime> SiparisKayitTarih { get; set; }
        public Nullable<System.DateTime> SiparisTeslimTarih { get; set; }
        public string SiparisAciklama { get; set; }
    
        public virtual MusteriTbl MusteriTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetayTbl> SiparisDetayTbl { get; set; }
    }
}
