//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunTbl()
        {
            this.SiparisDetayTbl = new HashSet<SiparisDetayTbl>();
        }
    
        public int UrunID { get; set; }
        public string UrunAdi { get; set; }
        public string BarkodNO { get; set; }
        public Nullable<int> StokAdeti { get; set; }
        public Nullable<decimal> Fiyati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetayTbl> SiparisDetayTbl { get; set; }
    }
}
